### ISSUE TITLE
Not working in Waterofx Browser

### ISSUE THREAD

**Issue by Erreur32** [cadars/photosheet#2]
With Waterfox version : G4.0.5.1 (64-bit)  I can not open/clic on any pictures.

Not tested in Firefox.

On my Chrome it works perfectly and looks nice ;)

Let me know if you need more details.

**Comment by cadars** [comment]
Thanks. Let me know if it now works for you?

**Comment by Erreur32** [comment]
Yes it's Working now , we can clic  on images and it's opening  BUT keyboard shortcut seem not working .

Only if you clic with mouse on left or right of the image to have a next image.

i have also tried to disable all plugin i have without success.
