### ISSUE TITLE
Touble in php to htnl!

### ISSUE THREAD

**Issue by kawayixixing** [cadars/photosheet#3]
i clone your rep, test in local, i have installed php,(PHP 7.4.3 (cli) (built: Mar  2 2022 15:36:52) ( NTS )). i modify nothing at source code. i use `php photosheet.php > index.html`, then i get error. **PHP Notice:  Only variables should be passed by reference in /home/freheit/Documents/200Life/207Tangtam/05Website/photosheet_bak/photosheet.php on line 22**, i don't know how to fix it. thanks for your attention!

**Comment by cadars** [comment]
I pushed a fix (tested with PHP 7.4 and 8.0) let me know if that works for you!

**Comment by kawayixixing** [comment]
![image](https://user-images.githubusercontent.com/45343530/160734292-7a180a2d-b5c8-4f42-bb9c-4c661d50b2f6.png)
it works but also it back to me some errors.

**Comment by kawayixixing** [comment]
https://kawayixixing.github.io/Freheit_box/tangram/index.html
i use your codes, building this htnl page. thanks your very much!

**Comment by cadars** [comment]
Glad it works for you! I can’t reproduce the errors you got (using PHP 7.4.21) so I’ll consider this bug fixed.
